Vagrant.configure("2") do |config|
  config.vm.hostname = "control-node"
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.56.2"
  
  config.vm.synced_folder ".", "/vagrant", type: "nfs" # in case of using Windows, search for vagrant plugin about nfs  
  config.vm.provision "shell", path: "provision.sh"
end