---
- name: Set up Java Server Application
  hosts: app01
  user: vagrant
  become: yes

  vars:
    - dbhost: "db01"
    - dbname: "notes"
    - dbusername: "notesapp"
    - dbpassword: "devopsmaonamassa"

  tasks:
    - name: Setup hosts lab ansible
      lineinfile:
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
        - 192.168.56.2 control-node
        - 192.168.56.3 app01
        - 192.168.56.4 db01
    - name: Add app user
      user:
        name: app
        comment: Default app user
        uid: 23
    - name: Installing Java JDK 1.8
      yum:
        name: java-1.8.0-openjdk-devel
        state: latest
    - name: Add JDK to Environment Path
      lineinfile:
        path: /etc/profile
        line: "export PATH=$PATH:/usr/lib/jvm/java-1.8.0-openjdk/bin"
        state: present
        create: yes
    - name: Checking if JDK was installed correctly
      shell: |
        java -version
        javac -version
      register: jdk_version
    - name: Maven Download
      get_url:
        url: https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.0/apache-maven-3.9.0-bin.tar.gz
        dest: /opt/apache-maven-3.9.0-bin.tar.gz
    - name: Maven's Package Unzip
      ansible.builtin.unarchive:
        src: /opt/apache-maven-3.9.0-bin.tar.gz
        dest: /opt/
        remote_src: yes
    - name: Create link command to mvn
      file:
        src: /opt/apache-maven-3.9.0/bin/mvn
        dest: /bin/mvn
        state: link
    - name: Creating app directory
      file:
        path: /opt/notes/
        state: directory
        owner: app
        group: app
    - name: Installing git client
      yum:
        name: git
        state: latest
    - name: Git Clone notes
      git:
        repo: "https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git"
        dest: /opt/notes/
        clone: yes
        force: yes
    - name: Setup POM.XML file
      template:
        src: pom.xml
        dest: /opt/notes/pom.xml
        owner: app
    - name: Setup DB properties file
      template:
        src: application.properties
        dest: /opt/notes/src/main/resources/application.properties
        owner: app
    - name: Generating app package
      command: mvn -f /opt/notes/pom.xml package -Dmaven.test.skip=true
    - name: Register current package version
      shell:
        cmd: mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\['
        chdir: /opt/notes
      register: app_version
    - name: Setup systemd service
      template:
        src: etc/systemd/system/notes.service
        dest: /etc/systemd/system/notes.service
      notify: reload daemon
    - name: Starting notes service
      service:
        name: notes
        state: restarted

  roles:
    - configuracao-default-so

  handlers:
    - name: reload app
      systemd:
        state: restarted
        daemon_reload: yes
        name: "notes"
    - name: reload daemon
      systemd:
        daemon_reexec: yes
