- name: Update of all os packages
  yum:
    name: "*"
    state: latest

- name: Installing git client
  yum:
    name: git
    state: latest

- name: Setup hosts lab ansible
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{item}}"
  with_items:
    - 192.168.56.2 control-node
    - 192.168.56.3 app01
    - 192.168.56.4 db01